### ISSUE TITLE
Not found in marketplace

### ISSUE THREAD

**Issue by mirelon** [KartanHQ/intellij-turbo#81]
### Describe the bug

Not found on web search:
![image](https://github.com/KartanHQ/intellij-turbo/assets/1101497/e71f3a2f-7312-4eba-b5ad-be32a9133a68)

Not found in IDE marketplace (IntelliJ IDEA 2023.3.4 (Ultimate Edition))
![image](https://github.com/KartanHQ/intellij-turbo/assets/1101497/b808737a-fecf-45f6-aa79-e2fc9fe830df)

**Comment by Keiishu** [comment]
Re-opening this issue, as the plugin is still nowhere to be found in the Marketplace.
